version: '2.1'
services:
  landing:
    build: ./
    volumes:
      - ./:/var/www
    entrypoint: /bin/bash
    command: /var/www/start-dev.sh
    ports:
      - 3000:3000
    environment:
      - BASE_URL
      - BROWSER_URL